import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black p-10">
        <div className="container mx-auto">
          <div className="bg-slate-900 rounded-[3rem] p-5">
            <div className="text-white">
              <div className="grid grid-cols-2   absolutex w-fullx  m-4 ">
                <div className="max-w-xsx text-left">
                  <p>Longitude - 28.12312</p>
                  <p>Latitude - 77.3273</p>
                </div>
                <div className="max-w-xsx text-right">
                  <p>Chrome v119.0.0.0 </p>
                  <p>Windows 10</p>
                </div>
              </div>
              <div className="px-20 ">{children}</div>
              <div className="grid grid-cols-3   absolutex w-fullx  m-4 ">
                <div className="max-w-xsx text-left">
                  <p>Local time - 16:05</p>
                  <p>Time Spend - 00:05</p>
                </div>
                <div>
                  <div className="text-center rounded-[4rem] bg-slate-800 py-5 px-7 flex justify-between">
                    <Link className="text-2xl text-center" href="/">Home</Link>
                    <Link className="text-2xl text-center" href="/projects">Proyects</Link>
                    <Link className="text-2xl text-center" href="/about">About</Link>
                    <Link className="text-2xl text-center" href="/contact">Contact</Link>
                  </div>
                </div>
                <div className="max-w-xsx text-right">
                  <p>122.16153938</p>
                  <p>Peru, Brasil and Bolivia</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
